import { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../services/firebase';
import { legalAPI } from '../../services/api';
import {
    FileText,
    Calendar,
    Clock,
    MapPin,
    User,
    Users,
    AlertTriangle,
    Download,
    ArrowLeft,
    CheckCircle
} from 'lucide-react';
import toast from 'react-hot-toast';

const FIRGenerator = ({ onBack }) => {
    const { user, userProfile } = useAuth();
    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);
    const [generatedFIR, setGeneratedFIR] = useState(null);
    const [formData, setFormData] = useState({
        incidentDate: '',
        incidentTime: '',
        incidentLocation: '',
        description: '',
        accusedName: '',
        accusedDescription: '',
        witnessName: '',
        witnessContact: '',
    });

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (!formData.incidentDate || !formData.incidentLocation || !formData.description) {
            toast.error('Please fill in all required fields');
            return;
        }

        setLoading(true);

        try {
            // Try backend FIR generation (uses OpenAI if configured)
            const resp = await legalAPI.generateFIR({ incidentDetails: formData });

            const firText = resp?.data?.firText;
            const firId = resp?.data?.firId;

            if (firText) {
                setGeneratedFIR({ id: firId, text: firText });
                setStep(3);
                toast.success('FIR draft generated successfully!');
            } else {
                // Fallback to local generator
                const fallback = generateFIRDraft(formData);
                const firRef = await addDoc(collection(db, 'firDrafts'), {
                    userId: user.uid,
                    generatedAt: serverTimestamp(),
                    incidentDetails: formData,
                    generatedText: fallback,
                });
                setGeneratedFIR({ id: firRef.id, text: fallback });
                setStep(3);
                toast.success('FIR draft generated (fallback)');
            }

        } catch (error) {
            console.error('FIR generation error:', error);
            // Fallback to local generator
            const fallback = generateFIRDraft(formData);
            try {
                const firRef = await addDoc(collection(db, 'firDrafts'), {
                    userId: user.uid,
                    generatedAt: serverTimestamp(),
                    incidentDetails: formData,
                    generatedText: fallback,
                });
                setGeneratedFIR({ id: firRef.id, text: fallback });
                setStep(3);
                toast.success('FIR draft generated (fallback)');
            } catch (e) {
                toast.error('Failed to generate FIR. Please try again.');
            }
        } finally {
            setLoading(false);
        }
    };

    const generateFIRDraft = (data) => {
        const currentDate = new Date().toLocaleDateString('en-IN', {
            day: '2-digit',
            month: 'long',
            year: 'numeric'
        });

        return `══════════════════════════════════════════════════════════════
                    DRAFT FIRST INFORMATION REPORT (FIR)
══════════════════════════════════════════════════════════════

⚠️ IMPORTANT DISCLAIMER:
This is a DRAFT document generated by SafeHer AI. It is intended to help 
you organize information before visiting a police station. This is NOT a 
legally filed FIR. Please review with a legal professional before 
submission to authorities.

══════════════════════════════════════════════════════════════

TO: The Station House Officer
Police Station: _________________________
District: _________________________

SUBJECT: Request for Registration of FIR

COMPLAINANT DETAILS:
────────────────────────────────────────────────────────────────
Name: ${userProfile?.name || '[Your Full Name]'}
Phone: ${userProfile?.phone || '[Your Phone Number]'}
Address: [Your Complete Address]
Date of Filing: ${currentDate}

══════════════════════════════════════════════════════════════
                        INCIDENT DETAILS
══════════════════════════════════════════════════════════════

Date of Incident: ${data.incidentDate}
Approximate Time: ${data.incidentTime || '[Not Specified]'}
Place of Incident: ${data.incidentLocation}

────────────────────────────────────────────────────────────────
DESCRIPTION OF INCIDENT:
────────────────────────────────────────────────────────────────

${data.description}

══════════════════════════════════════════════════════════════
                    ACCUSED PERSON DETAILS
══════════════════════════════════════════════════════════════
${data.accusedName ? `
Name (if known): ${data.accusedName}
Description: ${data.accusedDescription || '[Physical description, if applicable]'}
` : 'Accused person details unknown at this time.'}

══════════════════════════════════════════════════════════════
                      WITNESS INFORMATION
══════════════════════════════════════════════════════════════
${data.witnessName ? `
Witness Name: ${data.witnessName}
Contact: ${data.witnessContact || '[Not provided]'}
` : 'No witnesses to report at this time.'}

══════════════════════════════════════════════════════════════
                    APPLICABLE LEGAL SECTIONS
══════════════════════════════════════════════════════════════

[To be determined by police/legal authority. Common sections include:]
• IPC Section 354 - Assault to outrage modesty
• IPC Section 354A - Sexual harassment
• IPC Section 354B - Assault with intent to disrobe
• IPC Section 354C - Voyeurism
• IPC Section 354D - Stalking
• IPC Section 376 - Rape
• IPC Section 509 - Word, gesture, or act to insult modesty

══════════════════════════════════════════════════════════════
                         PRAYER/REQUEST
══════════════════════════════════════════════════════════════

I, the undersigned, request that this FIR be registered and 
appropriate action be taken against the accused person(s) as 
per the law.

I solemnly declare that the information provided above is true 
and correct to the best of my knowledge and belief.


Signature: ________________________

Date: ${currentDate}

Place: ________________________


══════════════════════════════════════════════════════════════
                        END OF DRAFT FIR
══════════════════════════════════════════════════════════════

Generated by SafeHer - AI-Powered Women Safety Platform
This document was created on ${currentDate}

⚠️ REMINDER: This is a preliminary draft. Please:
1. Review all details carefully
2. Consult with a lawyer if possible
3. Take this draft to the nearest police station
4. Police will create the official FIR with proper format
`;
    };

    const downloadFIR = () => {
        if (!generatedFIR) return;

        const blob = new Blob([generatedFIR.text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `FIR_Draft_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success('FIR draft downloaded!');
    };

    const copyToClipboard = () => {
        if (!generatedFIR) return;
        navigator.clipboard.writeText(generatedFIR.text).then(() => {
            toast.success('Copied to clipboard!');
        });
    };

    return (
        <div className="page-container pt-6 pb-24">
            <div className="container">
                {/* Header */}
                <div className="flex items-center gap-3 mb-6">
                    {onBack && (
                        <button onClick={onBack} className="p-2 -ml-2 hover:bg-gray-100 rounded-lg">
                            <ArrowLeft size={20} />
                        </button>
                    )}
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900">FIR Draft Generator</h1>
                        <p className="text-sm text-gray-500">Create a draft for police report</p>
                    </div>
                </div>

                {/* Disclaimer */}
                <div className="disclaimer mb-6">
                    <strong>⚠️ Important:</strong> This tool creates a DRAFT FIR to help you organize
                    information. The final FIR must be filed at a police station. Always consult
                    a legal professional for serious matters.
                </div>

                {/* Progress Steps */}
                <div className="flex items-center gap-2 mb-6">
                    {[1, 2, 3].map((s) => (
                        <div key={s} className="flex items-center">
                            <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium ${step >= s
                                    ? 'bg-blue-600 text-white'
                                    : 'bg-gray-200 text-gray-500'
                                }`}>
                                {step > s ? <CheckCircle size={16} /> : s}
                            </div>
                            {s < 3 && (
                                <div className={`w-12 h-1 ${step > s ? 'bg-blue-600' : 'bg-gray-200'}`} />
                            )}
                        </div>
                    ))}
                </div>

                {/* Step 1: Incident Details */}
                {step === 1 && (
                    <div className="card slide-up">
                        <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                            <Calendar size={20} className="text-blue-600" />
                            Incident Details
                        </h2>

                        <div className="space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="label">Date of Incident *</label>
                                    <input
                                        type="date"
                                        name="incidentDate"
                                        value={formData.incidentDate}
                                        onChange={handleChange}
                                        className="input"
                                        required
                                    />
                                </div>
                                <div>
                                    <label className="label">Approximate Time</label>
                                    <input
                                        type="time"
                                        name="incidentTime"
                                        value={formData.incidentTime}
                                        onChange={handleChange}
                                        className="input"
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="label">Location of Incident *</label>
                                <div className="relative">
                                    <MapPin className="absolute left-3 top-3 text-gray-400" size={18} />
                                    <input
                                        type="text"
                                        name="incidentLocation"
                                        value={formData.incidentLocation}
                                        onChange={handleChange}
                                        placeholder="Enter complete address or landmark"
                                        className="input pl-10"
                                        required
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="label">Description of Incident *</label>
                                <textarea
                                    name="description"
                                    value={formData.description}
                                    onChange={handleChange}
                                    placeholder="Describe what happened in detail. Include sequence of events, any injuries, property damage, etc."
                                    className="input min-h-[150px] resize-none"
                                    required
                                />
                            </div>

                            <button
                                onClick={() => setStep(2)}
                                disabled={!formData.incidentDate || !formData.incidentLocation || !formData.description}
                                className="btn btn-primary w-full"
                            >
                                Continue
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 2: Accused & Witness */}
                {step === 2 && (
                    <div className="card slide-up">
                        <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                            <Users size={20} className="text-blue-600" />
                            Accused & Witness Details
                        </h2>

                        <p className="text-sm text-gray-500 mb-4">
                            These fields are optional. Fill in if you have this information.
                        </p>

                        <div className="space-y-4">
                            <div>
                                <label className="label">Accused Person's Name</label>
                                <div className="relative">
                                    <User className="absolute left-3 top-3 text-gray-400" size={18} />
                                    <input
                                        type="text"
                                        name="accusedName"
                                        value={formData.accusedName}
                                        onChange={handleChange}
                                        placeholder="Name if known"
                                        className="input pl-10"
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="label">Accused Description</label>
                                <textarea
                                    name="accusedDescription"
                                    value={formData.accusedDescription}
                                    onChange={handleChange}
                                    placeholder="Physical description, identifying features, clothing, vehicle details, etc."
                                    className="input min-h-[80px] resize-none"
                                />
                            </div>

                            <hr className="my-4" />

                            <div>
                                <label className="label">Witness Name</label>
                                <input
                                    type="text"
                                    name="witnessName"
                                    value={formData.witnessName}
                                    onChange={handleChange}
                                    placeholder="Name of any witness"
                                    className="input"
                                />
                            </div>

                            <div>
                                <label className="label">Witness Contact</label>
                                <input
                                    type="text"
                                    name="witnessContact"
                                    value={formData.witnessContact}
                                    onChange={handleChange}
                                    placeholder="Phone number or address"
                                    className="input"
                                />
                            </div>

                            <div className="flex gap-3">
                                <button
                                    onClick={() => setStep(1)}
                                    className="btn btn-secondary flex-1"
                                >
                                    Back
                                </button>
                                <button
                                    onClick={handleSubmit}
                                    disabled={loading}
                                    className="btn btn-primary flex-1"
                                >
                                    {loading ? (
                                        <>
                                            <span className="spinner" />
                                            Generating...
                                        </>
                                    ) : (
                                        <>
                                            <FileText size={18} />
                                            Generate FIR Draft
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {/* Step 3: Generated FIR */}
                {step === 3 && generatedFIR && (
                    <div className="slide-up">
                        <div className="bg-green-50 border border-green-200 rounded-xl p-4 mb-4">
                            <div className="flex items-center gap-2 text-green-700">
                                <CheckCircle size={20} />
                                <span className="font-semibold">FIR Draft Generated Successfully!</span>
                            </div>
                        </div>

                        <div className="card mb-4">
                            <div className="flex items-center justify-between mb-4">
                                <h2 className="font-semibold text-gray-900">Your FIR Draft</h2>
                                <div className="flex gap-2">
                                    <button
                                        onClick={copyToClipboard}
                                        className="btn btn-secondary text-sm py-2 px-3"
                                    >
                                        Copy
                                    </button>
                                    <button
                                        onClick={downloadFIR}
                                        className="btn btn-primary text-sm py-2 px-3"
                                    >
                                        <Download size={16} />
                                        Download
                                    </button>
                                </div>
                            </div>

                            <div className="bg-gray-50 rounded-lg p-4 max-h-[400px] overflow-y-auto">
                                <pre className="text-xs whitespace-pre-wrap font-mono text-gray-700">
                                    {generatedFIR.text}
                                </pre>
                            </div>
                        </div>

                        <div className="card bg-blue-50 border-blue-200">
                            <h3 className="font-semibold text-blue-900 mb-2">Next Steps:</h3>
                            <ol className="text-sm text-blue-700 space-y-2 list-decimal list-inside">
                                <li>Download or copy this FIR draft</li>
                                <li>Review all details carefully</li>
                                <li>Visit your nearest police station</li>
                                <li>Show this draft to the officer</li>
                                <li>They will file the official FIR</li>
                            </ol>
                        </div>

                        <button
                            onClick={() => {
                                setStep(1);
                                setFormData({
                                    incidentDate: '',
                                    incidentTime: '',
                                    incidentLocation: '',
                                    description: '',
                                    accusedName: '',
                                    accusedDescription: '',
                                    witnessName: '',
                                    witnessContact: '',
                                });
                                setGeneratedFIR(null);
                            }}
                            className="btn btn-secondary w-full mt-4"
                        >
                            Create Another FIR Draft
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default FIRGenerator;
